f = open('разделенный на строки Тургенев.txt')
name = f.readline()
text = f.read()
print('Название произведения:', name)
print('=============================')
print('Текст произведения:')
print(text)